version: 2.1

jobs:
  build:
    docker:
      - image: node:14

    working_directory: /app

    steps:
      - checkout
      - run:
          name: Install Dependensi
          command: npm install
      - run:
          name: Jalankan Test
          command: npm test
      - run:
          name: Development
          command: npm run development
  deploy:
    docker:
      - image: node:14
    
    steps:
      - run: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build
  deploy:
    jobs:
      - deploy
